
"use client";
import { Links } from "@/components/links";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useSelectedLayoutSegment } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  notifications,
  users,

}: Readonly<{
  children: React.ReactNode;
  notifications: React.ReactNode;
  users: React.ReactNode;

}>) {
  const loginSegment = useSelectedLayoutSegment("notifications")
  
  return (
    <section>
        {children} 
        {users}
        {loginSegment === "archived" && <h2>archived </h2>} 
        {notifications}



    </section>
  );
}
