"use client";
import { Links } from "@/components/links";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  modalview
}: Readonly<{
  children: React.ReactNode;
  modalview: React.ReactNode

}>) {
  return (
    <section>

        <Links />
        {children} 
        {modalview}

    </section>
  );
}
